name: Check Markdown links

on:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-extension: '.mdx'
          use-quiet-mode: 'yes'
          config-file: '.github/mdl.config.json'
